### ISSUE TITLE
Compose starts with EACCES: permission denied

### ISSUE THREAD

**Issue by felixdollack** [ad3m3r5/scratch-map#34]
I am trying to run scratch-map in portioner with the following settings:
```
services:
  scratch-map:
    container_name: scratch-map
    image: ad3m3r5/scratch-map:latest
    restart: unless-stopped
    ports:
      - "4000:8080"
    environment:
      ADDRESS: '0.0.0.0'
      PORT: 4000
      DATA_DIR: '/my-data-dir'
      LOG_LEVEL: 'INFO'
    volumes:
      - ./scratch-map-data:/my-data-dir

volumes:
  scratch-map-data:
    name: scratch-map-appdata
```

But the logs show that the director can not be accessed.
```
node:fs:596
  handleErrorFromBinding(ctx);
  ^
Error: EACCES: permission denied, open '/my-data-dir/.db.json.tmp'
    at Object.openSync (node:fs:596:3)
    at writeFileSync (node:fs:2322:35)
    at TextFileSync.write (file:///app/node_modules/lowdb/lib/adapters/node/TextFile.js:51:9)
    at JSONFileSync.write (file:///app/node_modules/lowdb/lib/adapters/node/DataFile.js:43:23)
    at LowSync.write (file:///app/node_modules/lowdb/lib/core/Low.js:44:26)
    at createConnection (file:///app/utils/database.js:37:6)
    at file:///app/server.js:42:7
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/my-data-dir/.db.json.tmp'
}
Node.js v18.20.4
```

Any idea what could be wrong here?
Does that folder `/my-data-dir` even exist inside the container?

**Comment by ad3m3r5** [comment]
Hey @felixdollack! I added more information than you were probably looking for, but I just wanted to make sure everything was as clear as possible.

It looks like there might be a mix-up or two with your compose config.

## Docker
You pass a local directory of `scratch-map-data` in the container config, but then you also create a docker volume at the bottom. `Bind Mount` vs `Volume`.

#### Bind Mount
If you want to pass the local directory, make sure your local `scratch-map-data` directory has the correct permissions. Since the container runs as the user `node` with a uid/gid of `1000`, you can use the command `chown -R 1000:1000 ./scratch-map-data` to fix those permissions (may require sudo). So your final `compose.yaml` file would look like this:
```
services:
  scratch-map:
    container_name: scratch-map
    image: ad3m3r5/scratch-map:latest
    restart: unless-stopped
    ports:
      - "4000:3000"
    environment:
      DATA_DIR: '/my-data-dir'
    volumes:
      - ./scratch-map-data:/my-data-dir
```

#### Volume
If you want to use the docker volume, I would suggest removing the `DATA_DIR` variable and then mounting the volume to the default directory (`/app/data`). The final `compose.yaml` file:
```
services:
  scratch-map:
    container_name: scratch-map
    image: ad3m3r5/scratch-map:latest
    restart: unless-stopped
    ports:
      - "4000:3000"
    volumes:
      - scratch-map-data:/app/data

volumes:
  scratch-map-data:
    name: scratch-map-appdata
```


## Port

#### Default
The ENV variable of `PORT` is set to `4000`, which runs the node process *inside* the container on port `4000`, but then the section that maps your local port `4000` to the internal port specifies `8080`. To make that part of your config work, you can use:
```
    ports:
      - "4000:3000"
```
This leaves off the environment variable altogether and maps your systems port `4000` to the default internal port of `3000`. I applied this fix to the above "final" `compose.yaml` examples.

#### Custom
The below will run node on `8080` *internally* and still expose it on port 4000 of your system.
```
    ports:
      - "4000:8080"
    environment:
      PORT: 8080
```

## Side Note
In the example final files, I did remove the environment variables that were set to defaults, as they do not need to be explicitly set unless they are different. I should probably remove them from the example `compose.yaml` files, as it probably causes more confusion than help.

`ADDRESS`, `PORT`, and `LOG_LEVEL`
